states = [
    'NY, CA, IL, FL, TX, PA, GA, DC, MA, AZ, WA, MI, MN, CO, MD, NV, OR, MO, OH, IN, NC, VA, WI, RI, UT, TN, LA, KY, '
    'OK, CT, NY, NE, HI, NM, AL, SC, KS, IA, AR, ID, MS, NJ, AK, NH, '
    'ND, ME, SD, WV, MT, VT, WY, DE']

cities = ["New York, Los Angeles, Chicago, Miami, Dallas, Philadelphia, Houston, Atlanta, Washington, Boston, "
          "Phoenix, Seattle, San Francisco, Detroit, San Diego, Minneapolis, Tampa, Denver, Riverside, Baltimore, "
          "Las Vegas, Portland, San Antonio, St. Louis, Sacramento, Orlando, San Jose, Cleveland, Pittsburgh, Austin, "
          "Cincinnati, Kansas City, Indianapolis, Columbus, Charlotte, Virginia Beach, Milwaukee, Providence, "
          "Jacksonville, Salt Lake City, Nashville, Richmond, Memphis, Raleigh, New Orleans, Louisville, "
          "Oklahoma City, Bridgeport, Buffalo, Fort Worth, Hartford, Tucson, Omaha, El Paso, Honolulu, McAllen, "
          "Albuquerque, Birmingham, Dayton, Rochester, Fresno, Allentown, Tulsa, Cape Coral, Concord, "
          "Colorado Springs, Charleston, Springfield, Grand Rapids, Mission Viejo, Albany, Knoxville, Bakersfield, "
          "Ogden, Baton Rouge, Akron, New Haven, Columbia, Mesa, Palm Bay, Provo, Worcester, Murrieta, Wichita, "
          "Toledo, Des Moines, Long Beach, Port St. Lucie, Denton, Madison, Reno, Little Rock, Oakland, Durham, "
          "Winston-Salem, Indio, Palm Coast, Chattanooga, Spokane, Syracuse, Arlington, Stockton, Augusta, Boise, "
          "Oxnard, Scranton, Modesto, Aurora, Youngstown, Fayetteville, Anaheim, Victorville, Lancaster, Greensboro, "
          "Corpus Christi, Fort Wayne, Santa Ana, Flint, Jackson, Santa Rosa, Lansing, Lexington, Ann Arbor, "
          "Henderson, Huntsville, Mobile, Fort Collins, Asheville, Santa Clarita, St. Paul, Antioch, Lakeland, "
          "Trenton, Lincoln, Anchorage, Plano, Irvine, Davenport, Rockford, Newark, South Bend, Shreveport, Savannah, "
          "Chula Vista, Eugene, Canton, Lubbock, Reading, Salem, St. Petersburg, Lafayette, Laredo, Jersey City, "
          "Chandler, McKinney, Scottsdale, Killeen, Tallahassee, Peoria, Wilmington, Montgomery, Gilbert, Glendale, "
          "North Las Vegas, Chesapeake, Norfolk, Fremont, Kennewick, Garland, Irving, Visalia, Nashua, Hialeah, "
          "Evansville, Avondale, Brownsville, Gulfport, Appleton, Tacoma, San Bernardino, College Station, Kalamazoo, "
          "Thousand Oaks, Roanoke, Fontana, Moreno Valley, Fargo, Green Bay, Amarillo, Santa Barbara, Gainesville, "
          "Frisco, Yonkers, Huntington Beach, Deltona, Tempe, Overland Park, Grand Prairie, Waco, Salinas, Waterbury, "
          "Clarksville, Cedar Rapids, Sioux Falls, Ontario, Erie, Vancouver, Nampa, Gastonia, Fort Lauderdale, "
          "Murfreesboro, High Point, Newport News, Rancho Cucamonga, Hemet, Danbury, Oceanside, Elk Grove, "
          "Pembroke Pines, Vallejo, Garden Grove, Medford, Cary, Corona, Manchester, Champaign, Alexandria, Hayward, "
          "Lakewood, Lake Charles, Odessa, Tuscaloosa, Warner Robins, Palmdale, Hollywood, Midland, Macon, Sunnyvale, "
          "Pomona, Escondido, Pasadena, New Bedford, Fairfield, Naperville, Bellevue, Topeka, Joliet, Beaumont, "
          "Paterson, Merced, Pueblo, Tyler, Torrance, Yuma, Surprise, Athens, Roseville, Thornton, Miramar, Mesquite, "
          "Santa Maria, Olathe, Carrollton, Orange, Fullerton, Greeley, Las Cruces, West Valley City, Hampton, "
          "Warren, Bloomington, Coral Springs, Round Rock, Yakima, Sterling Heights, Kent, Bellingham, Santa Clara, "
          "Racine, Greenville, Stamford, Elizabeth, Lynchburg, Simi Valley, Fort Smith, Kenosha, Norman, Boulder, "
          "Abilene, Pearland, Berkeley, Richardson, Redding, Arvada, St. George, Billings, Duluth, Rock Hill, "
          "Cambridge, Sugar Land, Iowa City, Chico, Clearwater, Independence, West Jordan, El Monte, Carlsbad, "
          "North Charleston, Temecula, Clovis, Meridian, Westminster, Costa Mesa, Pompano Beach, West Palm Beach, "
          "Waterloo, Everett, Santa Fe, Downey, Lowell, Centennial, Elgin, Broken Arrow, Miami Gardens, Bend, "
          "Burlington, Sandy Springs, Gresham, Lewisville, Hillsboro, San Buenaventura, Inglewood, League City, "
          "Turlock, Sioux City, Davie, Daly City, Allen, West Covina, Sparks, Wichita Falls, San Mateo, Norwalk, "
          "Rialto, Manteca, El Cajon, Burbank, Longmont, Renton, Vista, Vacaville, Edinburg, Carmel, Spokane Valley, "
          "San Angelo, Longview, Tracy, Boca Raton, Lee's Summit, Rio Rancho, Beaverton, Lawrence, Orem, San Marcos, "
          "Sandy, Federal Way, Hesperia, Brockton, Compton, Fishers, Sunrise, Roswell, Menifee, Plantation, Quincy, "
          "Portsmouth, Chino, Lynn, Edmond, Dearborn, Livonia, South Gate, Lawton, Missoula, Rapid City, Suffolk, "
          "Mount Pleasant, Carson, Livermore, Santa Monica, Fall River, Miami Beach, San Leandro, O'Fallon, Newton, "
          "Muncie, Citrus Heights, Decatur, Bryan, Waukegan, Hawthorne, Redwood City, Hoover, Lake Forest, Napa, "
          "Whittier, Clifton, Largo, Johns Creek, Newport Beach, Mission, Milpitas, Troy, Chino Hills, Alhambra, "
          "Melbourne, Mountain View, Buena Park, Pleasanton, Westland, Auburn, Cranston, Somerville, Folsom, "
          "Springdale, Deerfield Beach, Warwick, Cicero, Farmington Hills, Brooklyn Park, Plymouth, Cheyenne, Tustin, "
          "Perris, St. Joseph, Pharr, Loveland, Boynton Beach, New Rochelle, Jonesboro, Parma, Layton, Alameda, "
          "Baytown, Upland, Bellflower, San Ramon, Bethlehem, Wyoming, Hammond, Missouri City, Baldwin Park, Gary, "
          "Arlington Heights, Bolingbrook, Rochester Hills, Union City, Camden, Evanston, Apple Valley, Schaumburg, "
          "Southfield, New Britain, Waukesha, Pawtucket, Lauderhill, Redlands, Lynwood, Passaic, Palatine, "
          "Mount Vernon, Redondo Beach, Kenner, Schenectady"]
